language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
script:
  - yarn test
after_success:
  - yarn run coveralls
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - .export CC_TEST_REPORTER_ID=<d996233c1733a94b6bce8a9f0ed086e2a4e7ab1aa375dac3fab25cff67ded9ed> cc-test-reporter after-build --exit-code $?
